model_list:
  - model_name: gemma-4-31b-it
    litellm_params:
      model: gemini/gemma-4-31b-it
      api_key: os.environ/ZED_GEMINI_API_KEY
      rpm: 20

  - model_name: gemma-4-26b-a4b-it
    litellm_params:
      model: gemini/gemma-4-26b-a4b-it
      api_key: os.environ/ZED_GEMINI_API_KEY
      rpm: 20

  - model_name: gemini-3.1-flash-lite-preview
    litellm_params:
      model: gemini/gemini-3.1-flash-lite-preview
      api_key: os.environ/ZED_GEMINI_API_KEY
      rpm: 15

litellm_settings:
  drop_params: true
