services:
  opencode-proxy:
    image: docker.litellm.ai/berriai/litellm:main-stable
    container_name: opencode
    ports:
      - "4000:4000"
    volumes:
      - ./opencode/config.yaml:/app/config.yaml
    env_file:
      - ./.env
    command: ["--config", "/app/config.yaml"]
    restart: unless-stopped

  claude-proxy:
    image: docker.litellm.ai/berriai/litellm:main-stable
    container_name: claude
    ports:
      - "4001:4000"
    volumes:
      - ./claude/config.yaml:/app/config.yaml
    env_file:
      - ./.env
    command: ["--config", "/app/config.yaml"]
    restart: unless-stopped
